# Generated by Django 4.1.7 on 2023-03-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название меню')),
                ('title_slug', models.SlugField(verbose_name='Слаг для меню')),
                ('name', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('path', models.SlugField(max_length=255, verbose_name='Путь')),
                ('level', models.IntegerField(db_index=True, verbose_name='Уровень')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Список меню',
            },
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('title_slug', 'path'), name='unique slug/path'),
        ),
    ]
